export interface Product {
  id: number;
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  price: number | null;
  salePrice: number | null;
  image: string;
  description: string;
}

export interface Category {
  slug: string;
  name: string;
  nameEn: string;
  count: number;
}

export const categories: Category[] = [
  { slug: 'toperi', name: 'Toperi za kosu', nameEn: 'Hair Toppers', count: 7 },
  { slug: 'repovi-ravni', name: 'Repovi – Ravni 75cm', nameEn: 'Ponytails – Straight 75cm', count: 12 },
  { slug: 'repovi-kovrdzavi', name: 'Repovi – Kovrčavi 75cm', nameEn: 'Ponytails – Curly 75cm', count: 8 },
  { slug: 'repovi-uvijeni', name: 'Repovi – Uvijeni 80cm', nameEn: 'Ponytails – Wavy 80cm', count: 8 },
  { slug: 'repovi-premium', name: 'Premium Repovi 85–90cm', nameEn: 'Premium Ponytails 85–90cm', count: 2 },
  { slug: 'perike-prirodna-kosa', name: 'Perike – Prirodna kosa', nameEn: 'Wigs – Natural Hair', count: 7 },
  { slug: 'perike-proteinsko-vlakno', name: 'Perike – Proteinsko vlakno', nameEn: 'Wigs – Protein Fiber', count: 4 },
  { slug: 'ekstenzije', name: 'Ekstenzije – Prirodna kosa', nameEn: 'Extensions – Natural Hair', count: 4 },
  { slug: 'ekstenzije-klipse', name: 'Ekstenzije na klipse', nameEn: 'Clip-in Extensions', count: 3 },
  { slug: 'siskice', name: 'Šiškice', nameEn: 'Bangs / Fringe', count: 1 },
];

export const products: Product[] = [
  // ─── Hair Toppers ───
  {
    id: 1,
    slug: 'mono-topper-ombre-blonde',
    name: 'Mono Topper 3x5 – 41cm – Ombre Blonde',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-ombre-blonde.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, ombre blonde nijansa, dužina 41cm.',
  },
  {
    id: 2,
    slug: 'mono-topper-10-smedji',
    name: 'Mono Topper 3x5 – 41cm – #10 Smeđi',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-10-smedji.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, #10 smeđa nijansa, dužina 41cm.',
  },
  {
    id: 3,
    slug: 'mono-topper-613-plavi',
    name: 'Mono Topper 3x5 – 41cm – 613 Plavi',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-613-plavi.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, 613 plava nijansa, dužina 41cm.',
  },
  {
    id: 4,
    slug: 'mono-topper-4-6-smedji',
    name: 'Mono Topper 3x5 – #4/6 Smeđi',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-4-6-smedji.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, #4/6 smeđa nijansa.',
  },
  {
    id: 5,
    slug: 'mono-topper-platinum-blonde',
    name: 'Mono Topper 3x5 – Platinum Blonde',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-platinum-blonde.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, platinum blonde nijansa.',
  },
  {
    id: 6,
    slug: 'mono-topper-4-smedji-natural',
    name: 'Mono Topper 3x5 – #4 Smeđi (Natural)',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-4-smedji-natural.jpg',
    description: 'Premium mono topper 3x5 sa prirodnom ljudskom kosom, #4 smeđa nijansa, prirodan izgled.',
  },
  {
    id: 7,
    slug: 'mono-topper-4-smedji',
    name: 'Mono Topper – #4 Smeđi',
    category: 'Toperi za kosu',
    categorySlug: 'toperi',
    price: null,
    salePrice: null,
    image: '/images/topper-4-smedji-natural.jpg',
    description: 'Premium mono topper sa prirodnom ljudskom kosom, #4 smeđa nijansa.',
  },

  // ─── Ponytails - Straight 75cm ───
  {
    id: 8,
    slug: 'rep-6-smedji-ravni-75cm',
    name: 'Rep – #6 Smeđi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-6-smedji-ravni.jpeg',
    description: 'Rep za kosu #6 smeđi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 9,
    slug: 'rep-4-smedji-ravni-75cm',
    name: 'Rep – #4 Smeđi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-4-smedji-ravni.jpg',
    description: 'Rep za kosu #4 smeđi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 10,
    slug: 'rep-ombre-smedji-ravni-75cm',
    name: 'Rep – Ombre Smeđi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-smedji-ravni.png',
    description: 'Rep za kosu ombre smeđi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 11,
    slug: 'rep-613-ravni-75cm',
    name: 'Rep – 613 Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-613-ravni.png',
    description: 'Rep za kosu 613 plavi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 12,
    slug: 'rep-crni-ravni-75cm',
    name: 'Rep – Crni Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-crni-ravni.jpg',
    description: 'Rep za kosu crni, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 13,
    slug: 'rep-ombre-ash-blonde-ravni-75cm',
    name: 'Rep – Ombre Ash Blonde Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-ash-blonde-ravni.jpg',
    description: 'Rep za kosu ombre ash blonde, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 14,
    slug: 'rep-piano-ravni-75cm',
    name: 'Rep – Piano Pramenovi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-piano-ravni.png',
    description: 'Rep za kosu piano pramenovi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 15,
    slug: 'rep-ash-blonde-ravni-75cm',
    name: 'Rep – Ash Blonde Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ash-blonde-ravni.png',
    description: 'Rep za kosu ash blonde, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 16,
    slug: 'rep-ombre-pepeljasti-ravni-75cm',
    name: 'Rep – Ombre Pepeljasti Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-pepeljasti-ravni.png',
    description: 'Rep za kosu ombre pepeljasti, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 17,
    slug: 'rep-zlatno-plavi-ravni-75cm',
    name: 'Rep – Zlatno Plavi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-zlatno-plavi-ravni.jpg',
    description: 'Rep za kosu zlatno plavi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 18,
    slug: 'rep-10-smedji-ravni-75cm',
    name: 'Rep – #10 Smeđi Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-10-smedji-ravni.png',
    description: 'Rep za kosu #10 smeđi, ravni, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 19,
    slug: 'rep-ombre-rose-pink-ravni-75cm',
    name: 'Rep – Ombre Rose Pink Ravni 75cm',
    category: 'Repovi – Ravni 75cm',
    categorySlug: 'repovi-ravni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-rose-pink-ravni.webp',
    description: 'Rep za kosu ombre rose pink, ravni, dužina 75cm, premium kvalitet.',
  },

  // ─── Ponytails - Curly 75cm ───
  {
    id: 20,
    slug: 'rep-613-kovrdzavi-75cm',
    name: 'Rep – 613 Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-613-kovrdjavi.jpg',
    description: 'Rep za kosu 613 plavi, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 21,
    slug: 'rep-crni-kovrdzavi-75cm',
    name: 'Rep – Crni Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-crni-kovrdjavi.jpg',
    description: 'Rep za kosu crni, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 22,
    slug: 'rep-4-kovrdzavi-75cm',
    name: 'Rep – #4 Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 65,
    salePrice: null,
    image: '/images/rep-4-kovrdjavi.jpeg',
    description: 'Rep za kosu #4, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 23,
    slug: 'rep-kovrdzavi-75cm',
    name: 'Rep – Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-kovrdjavi-default.jpeg',
    description: 'Rep za kosu kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 24,
    slug: 'rep-ombre-pepeljasti-kovrdzavi-75cm',
    name: 'Rep – Ombre Pepeljasti Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-pepeljasti-kovrdjavi.jpg',
    description: 'Rep za kosu ombre pepeljasti, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 25,
    slug: 'rep-ombre-smedji-kovrdzavi-75cm',
    name: 'Rep – Ombre Smeđi Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-smedji-kovrdjavi.png',
    description: 'Rep za kosu ombre smeđi, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 26,
    slug: 'rep-piano-kovrdzavi-75cm',
    name: 'Rep – Piano Pramenovi Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-piano-kovrdjavi.png',
    description: 'Rep za kosu piano pramenovi, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 27,
    slug: 'rep-zlatno-plavi-kovrdzavi-75cm',
    name: 'Rep – Zlatno Plavi Kovrčavi 75cm',
    category: 'Repovi – Kovrčavi 75cm',
    categorySlug: 'repovi-kovrdzavi',
    price: 70,
    salePrice: 65,
    image: '/images/rep-zlatno-plavi-kovrdjavi.png',
    description: 'Rep za kosu zlatno plavi, kovrčavi, dužina 75cm, umjetno vlakno premium kvaliteta.',
  },

  // ─── Ponytails - Wavy 80cm ───
  {
    id: 28,
    slug: 'rep-613-uvijeni-80cm',
    name: 'Rep – 613 Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-613-uvijeni.png',
    description: 'Rep za kosu 613 plavi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 29,
    slug: 'rep-10-smedji-uvijeni-80cm',
    name: 'Rep – #10 Smeđi Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-10-smedji-uvijeni.jpeg',
    description: 'Rep za kosu #10 smeđi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 30,
    slug: 'rep-ombre-smedji-uvijeni-80cm',
    name: 'Rep – Ombre Smeđi Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-smedji-uvijeni.jpeg',
    description: 'Rep za kosu ombre smeđi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 31,
    slug: 'rep-6-smedji-uvijeni-80cm',
    name: 'Rep – #6 Smeđi Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-6-smedji-uvijeni.png',
    description: 'Rep za kosu #6 smeđi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 32,
    slug: 'rep-4-smedji-uvijeni-80cm',
    name: 'Rep – #4 Smeđi Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-4-smedji-uvijeni.jpeg',
    description: 'Rep za kosu #4 smeđi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 33,
    slug: 'rep-crni-uvijeni-80cm',
    name: 'Rep – Crni Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-crni-uvijeni.jpg',
    description: 'Rep za kosu crni, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 34,
    slug: 'rep-ombre-pepeljasti-uvijeni-80cm',
    name: 'Rep – Ombre Pepeljasti Uvijeni 80cm Premium',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-pepeljasti-uvijeni.jpg',
    description: 'Rep za kosu ombre pepeljasti, uvijeni, dužina 80cm, premium kvalitet.',
  },
  {
    id: 35,
    slug: 'rep-zlatno-plavi-uvijeni-80cm',
    name: 'Rep – Zlatno Plavi Uvijeni 80cm',
    category: 'Repovi – Uvijeni 80cm',
    categorySlug: 'repovi-uvijeni',
    price: 70,
    salePrice: 65,
    image: '/images/rep-zlatno-plavi-uvijeni.jpg',
    description: 'Rep za kosu zlatno plavi, uvijeni, dužina 80cm, umjetno vlakno premium kvaliteta.',
  },

  // ─── Premium Ponytails 85-90cm ───
  {
    id: 36,
    slug: 'rep-ombre-ash-blonde-90cm',
    name: 'Rep – Ombre Ash Blonde 90cm',
    category: 'Premium Repovi 85–90cm',
    categorySlug: 'repovi-premium',
    price: 70,
    salePrice: 65,
    image: '/images/rep-ombre-ash-blonde-90.png',
    description: 'Premium rep za kosu ombre ash blonde, dužina 90cm, 200g, umjetno vlakno premium kvaliteta.',
  },
  {
    id: 37,
    slug: 'rep-platinum-85cm-premium',
    name: 'Rep – Platinum 85cm 200g Premium',
    category: 'Premium Repovi 85–90cm',
    categorySlug: 'repovi-premium',
    price: 70,
    salePrice: 65,
    image: '/images/rep-platinum-85.png',
    description: 'Premium rep za kosu platinum, dužina 85cm, 200g, premium kvalitet.',
  },

  // ─── Wigs - Natural Human Hair ───
  {
    id: 38,
    slug: 'perika-bob-piano',
    name: 'Perika – Bob Pramenovi Piano',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 850,
    salePrice: 800,
    image: '/images/perika-bob-piano.jpg',
    description: 'Perika od prirodne ljudske kose, bob frizura sa piano pramenovima.',
  },
  {
    id: 39,
    slug: 'perika-balayage-ash-blonde',
    name: 'Perika – Balayage Ombre Ash Blonde',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1700,
    salePrice: 1600,
    image: '/images/perika-balayage-ash.jpg',
    description: 'Perika od prirodne ljudske kose, balayage ombre ash blonde nijansa.',
  },
  {
    id: 40,
    slug: 'perika-platinum-valovita',
    name: 'Perika – Platinum Valovita',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1700,
    salePrice: 1600,
    image: '/images/perika-platinum-valovita.jpg',
    description: 'Perika od prirodne ljudske kose, platinum valovita.',
  },
  {
    id: 41,
    slug: 'perika-ombre-platinum-valovita-premium',
    name: 'Perika – Ombre Platinum Valovita Premium',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1600,
    salePrice: 1550,
    image: '/images/perika-ombre-platinum.jpg',
    description: 'Premium perika od prirodne ljudske kose, ombre platinum valovita.',
  },
  {
    id: 42,
    slug: 'perika-valovita-balayage',
    name: 'Perika – Valovita Balayage',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1700,
    salePrice: 1600,
    image: '/images/perika-valovita-balayage.jpg',
    description: 'Perika od prirodne ljudske kose, valovita balayage nijansa.',
  },
  {
    id: 43,
    slug: 'perika-ombre-blonde-highlights',
    name: 'Perika – Ombre Blonde Highlights',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1600,
    salePrice: 1550,
    image: '/images/perika-ombre-blonde-highlights.jpg',
    description: 'Perika od prirodne ljudske kose, ombre blonde sa highlightovima.',
  },
  {
    id: 44,
    slug: 'perika-smedja-ravna-kratka',
    name: 'Perika – Smeđa Ravna Kratka',
    category: 'Perike – Prirodna kosa',
    categorySlug: 'perike-prirodna-kosa',
    price: 1200,
    salePrice: 1100,
    image: '/images/perika-smedja-ravna.jpg',
    description: 'Perika od prirodne ljudske kose, smeđa ravna kratka frizura.',
  },

  // ─── Wigs - Protein Fiber ───
  {
    id: 45,
    slug: 'perika-pv-balayage-valovita',
    name: 'Perika PV – Balayage Valovita',
    category: 'Perike – Proteinsko vlakno',
    categorySlug: 'perike-proteinsko-vlakno',
    price: 170,
    salePrice: null,
    image: '/images/perika-pv-balayage.jpg',
    description: 'Perika od proteinskog vlakna, balayage valovita, prirodan izgled.',
  },
  {
    id: 46,
    slug: 'perika-pv-piano-kovrdzava',
    name: 'Perika PV – Piano Kovrčava',
    category: 'Perike – Proteinsko vlakno',
    categorySlug: 'perike-proteinsko-vlakno',
    price: 180,
    salePrice: null,
    image: '/images/perika-pv-piano.jpg',
    description: 'Perika od proteinskog vlakna, piano kovrčava, prirodan izgled.',
  },
  {
    id: 47,
    slug: 'perika-pv-crna-valovita',
    name: 'Perika PV – Crna Valovita',
    category: 'Perike – Proteinsko vlakno',
    categorySlug: 'perike-proteinsko-vlakno',
    price: 160,
    salePrice: null,
    image: '/images/perika-pv-crna.jpg',
    description: 'Perika od proteinskog vlakna, crna valovita, prirodan izgled.',
  },
  {
    id: 48,
    slug: 'perika-pv-ombre-smedja',
    name: 'Perika PV – Ombre Smeđa Uvijena',
    category: 'Perike – Proteinsko vlakno',
    categorySlug: 'perike-proteinsko-vlakno',
    price: 160,
    salePrice: null,
    image: '/images/perika-pv-ombre-smedja.jpg',
    description: 'Perika od proteinskog vlakna, ombre smeđa uvijena, prirodan izgled.',
  },

  // ─── Extensions - Natural Human Hair ───
  {
    id: 49,
    slug: 'ekstenzije-tape-in-65cm',
    name: 'Prirodna kosa 65cm – Tape In – 1kg',
    category: 'Ekstenzije – Prirodna kosa',
    categorySlug: 'ekstenzije',
    price: 1200,
    salePrice: null,
    image: '/images/ext-tape-in.jpg',
    description: 'Ekstenzije od prirodne ljudske kose, tape in metoda, dužina 65cm, 1kg.',
  },
  {
    id: 50,
    slug: 'ekstenzije-keratin-65cm',
    name: 'Prirodna kosa 65cm – Keratin – 1kg',
    category: 'Ekstenzije – Prirodna kosa',
    categorySlug: 'ekstenzije',
    price: 1200,
    salePrice: null,
    image: '/images/ext-keratin.jpg',
    description: 'Ekstenzije od prirodne ljudske kose, keratin metoda, dužina 65cm, 1kg.',
  },
  {
    id: 51,
    slug: 'ekstenzije-premium-65cm',
    name: 'Prirodna kosa 65cm – Premium – 1kg',
    category: 'Ekstenzije – Prirodna kosa',
    categorySlug: 'ekstenzije',
    price: 1200,
    salePrice: null,
    image: '/images/ext-premium.jpg',
    description: 'Premium ekstenzije od prirodne ljudske kose, dužina 65cm, 1kg.',
  },
  {
    id: 52,
    slug: 'ekstenzije-klipse-65cm',
    name: 'Prirodna kosa – Klipse – 65cm – 1kg',
    category: 'Ekstenzije – Prirodna kosa',
    categorySlug: 'ekstenzije',
    price: 1200,
    salePrice: null,
    image: '/images/ext-klipse.jpg',
    description: 'Ekstenzije od prirodne ljudske kose na klipse, dužina 65cm, 1kg.',
  },

  // ─── Clip-in Extensions - Synthetic ───
  {
    id: 53,
    slug: 'klipse-svjetlije-nijanse',
    name: 'Ekstenzije Klipse – Svjetlije Nijanse',
    category: 'Ekstenzije na klipse',
    categorySlug: 'ekstenzije-klipse',
    price: 70,
    salePrice: 60,
    image: '/images/klipse-svjetlije.png',
    description: 'Ekstenzije na klipse, umjetno vlakno, svjetlije nijanse.',
  },
  {
    id: 54,
    slug: 'klipse-crna-ravna-uvijena',
    name: 'Ekstenzije Klipse – Crna Ravna i Uvijena',
    category: 'Ekstenzije na klipse',
    categorySlug: 'ekstenzije-klipse',
    price: 70,
    salePrice: 60,
    image: '/images/klipse-crna.jpg',
    description: 'Ekstenzije na klipse, umjetno vlakno, crna ravna i uvijena.',
  },
  {
    id: 55,
    slug: 'klipse-tamne-nijanse',
    name: 'Ekstenzije Klipse – Tamne Nijanse',
    category: 'Ekstenzije na klipse',
    categorySlug: 'ekstenzije-klipse',
    price: 70,
    salePrice: 60,
    image: '/images/klipse-tamne.png',
    description: 'Ekstenzije na klipse, umjetno vlakno, tamne nijanse.',
  },

  // ─── Bangs / Fringe ───
  {
    id: 56,
    slug: 'siskice-prirodna-kosa',
    name: 'Šiškice – Prirodna Ljudska Kosa',
    category: 'Šiškice',
    categorySlug: 'siskice',
    price: 55,
    salePrice: 45,
    image: '/images/siskice-prirodna.webp',
    description: 'Šiškice od prirodne ljudske kose, prirodan izgled.',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlug === categorySlug);
}

export function getFeaturedProducts(): Product[] {
  return [products[37], products[38], products[39], products[44], products[45], products[48], products[7], products[19]];
}

export function getBestSellers(): Product[] {
  return [products[0], products[10], products[20], products[28], products[36], products[52], products[55], products[46]];
}
